### ISSUE TITLE
Supported subtitle formats and file extensions

### ISSUE THREAD

**Issue by porg** [mpv-player/mpv.io#104]
I'm one of those willing to contribute, but not capable enough handling your mpv.io website building environment, hence my contribution here.

- This is the fulfillment of https://github.com/mpv-player/mpv/issues/11934

Section: https://mpv.io/manual/master/#subtitles

Gets this additional chapter, or possible integrated into the "Notes" section at the beginning.

### Supported subtitle formats and file extensions

- `mpv` supports exactly the same subtitle file formats that ffmpeg supports → See ffmpeg documentation → Support matrix [Subtitle-Formats](https://ffmpeg.org/general.html#Subtitle-Formats) → **"Decoding"** column → Compatibility symbol/remark.
- If you use [--sub-auto](#options-sub-auto) with option `exact` or `fuzzy` or `all` then mpv looks for matching files which in addition also have one of the supported "autoload" file extensions as defined in [external_files.c](https://github.com/mpv-player/mpv/blob/master/player/external_files.c) → [sub_exts](https://github.com/mpv-player/mpv/blob/master/player/external_files.c#L35) -- which as of 2023-08-10 are:

    `utf, utf8, utf-8, idx, sub, srt, rt, ssa, ass, mks, vtt, sup, scc, smi, lrc, pgs and NULL (that is a file without any extension)`

**Comment by sfan5** [comment]
Documentation changes can be contributed in the mpv repo under this folder: https://github.com/mpv-player/mpv/tree/master/DOCS/man
It's just RST and nothing fancy :)

**Comment by porg** [comment]
- I submitted it via https://github.com/mpv-player/mpv/pull/12126
- Did to the best of my knowledge and abilities. If it has any syntax mistakes or editorial mistakes, please correct them.
