### ISSUE TITLE
Package missing

### ISSUE THREAD

**Issue by surfer-nsk** [mpv-player/mpv.io#15]
current stable for Fedora
https://sourceforge.net/projects/handbrakefedora/

**Comment by wm4** [comment]
So, uh, why is this under ``handbrakefedora``?

**Comment by surfer-nsk** [comment]
originally intended for handbrake, later posted package mpv.
03 апр. 2015 г. 3:27 пользователь "V. Lang" <notifications@github.com>
написал:

**Comment by surfer-nsk** [comment]
I have placed repository on my domain, [here](http://surfernsk.ru/ "Fedora repository").
