### ISSUE TITLE
The SlackBuilds.org update for mpv.

### ISSUE THREAD

**Issue by jvvv** [mpv-player/mpv.io#21]
SlackBuild.org has released a new update, and my updated package for mpv-0.92 is included. I will leave my [github repo's version](https://github.com/jvvv/slackbuilds/tree/master/mpv), which bundles ffmpeg, intact for the time being; but the preferred package is again the one that is hosted on [SlackBuilds.org](http://slackbuilds.org/repository/14.1/multimedia/mpv). Thank for your continued patience while we were in the process of updating all our SlackBuilds that depended on ffmpeg to link against a more recent version (2.6.3).

**Comment by wm4** [comment]
Updated, along with some others.

(I wish we had an automatic way of doing this. All we want is to warn users before possibly installing an outdated version.)
