### ISSUE TITLE
Please update the image

### ISSUE THREAD

**Issue by Morecutter** [mpv-player/mpv.io#22]
See https://github.com/mpv-player/mpv/issues/2131

I hate this design from OSX 10.9. For my eyes not good. THX V.Lang

**Comment by Morecutter** [comment]
@ChrisK2 Can you update?

**Comment by pigoz** [comment]
I just changed it! I hope you like it more!

**Comment by Morecutter** [comment]
@pigoz 
Wow cool. Where has you this design? Is this for Windows or OSX?

**Comment by pigoz** [comment]
It's Qt Plasma! (on Linux)

**Comment by Morecutter** [comment]
I can not find on mpv wiki
