### ISSUE TITLE
An other repo to install MPV on Ubuntu

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv.io#28]
I think we should add this repo for Ubuntu on the installation page :

https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth

I use it for months, it works great and it's always up to date. Also it allow you to install MPV with VapourSynth compatibility and, if you want it, to install VapourSynth too.

Thank you.

**Comment by Paviluf** [comment]
You don't have copy / paste the right link in your commit ;)

**Comment by wm4** [comment]
Oops, fixed.
