### ISSUE TITLE
Put Fedora "RPM Fusion" in "Linux packages"

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv.io#29]
The Fedora "RPM Fusion" repo is up to date now ([v0.13](http://download1.rpmfusion.org/free/fedora/updates/testing/23/x86_64/repoview/mpv.html) but [v0.14](https://bugzilla.rpmfusion.org/show_bug.cgi?id=3853) is almost here) so we should put it back in "Linux packages" don't you think ?

By the way the link in the installation page seems to be outdated.

http://rpmfusion.org/

Thank you.

**Comment by wm4** [comment]
Didn't change the link - it seems to be fine and at least is specific to mpv?

**Comment by Paviluf** [comment]
Yeah in the devel folder of that [link](http://cvs.rpmfusion.org/viewvc/rpms/mpv/?root=free) it seems to be almost up to date.

I was thinking about something more like this one :

http://download1.rpmfusion.org/free/fedora/updates/testing/23/x86_64/repoview/mpv.html

**Comment by wm4** [comment]
That looks better, although slightly worried about the included version number. Changed.
