### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by joeffel** [mpv-player/mpv.io#43]
Please package it for OpenSUSE.

**Comment by wiiaboo** [comment]
http://software.opensuse.org/download.html?project=multimedia%3Aapps&package=mpv

**Comment by lachs0r** [comment]
OpenSUSE packages are provided in the main repository. Note that you should use FFmpeg packages from [Packman](https://packman.links2linux.de) (you can also get the mpv package for Leap there), or else codec support will be severely limited.
