### ISSUE TITLE
Latest version working under XP

### ISSUE THREAD

**Issue by er512** [mpv-player/mpv.io#59]
I search the latest version working under XP. Nothing found.
Is possibly to ad this old version as avalable download for XP users?

**Comment by wiiaboo** [comment]
https://web.archive.org/web/20160411060158/https://mpv.srsfckn.biz/
Here you go. 2015-10-29 is the last one working in XP.

**Comment by wiiaboo** [comment]
I don't think his builds existed yet.

**Comment by er512** [comment]
Shinchiro¨s builds started without XP support?I did not know it.
I search for mplayer clone working under XP, where is fixed inaccurate seek in file and  working seek setting less than 10 seconds.(optimal 1s)

mplayer, mplayer2, MPV has the same bug.
input.conf:
RIGHT seek +10
LEFT seek -10
great scattering:
>> 00:07:22 seek to 00:07:58, 00:08:01 seek to 00:08:41 etc.

**Comment by wiiaboo** [comment]
It's not a bug, just use `--hr-seek=yes` if you want exact seeks.

**Comment by lachs0r** [comment]
Neither mpv nor FFmpeg support Windows XP anymore, so this will not be possible.
If you want accurate seeking, use either the `--hr-seek` option or add `exact` to the seek lines in input.conf.

**Comment by er512** [comment]
Very thank !
This is working in MPV and Mplayer2, with small syntax difference
mpv: --hr-seek=yes
mplayer2: -hr-seek on 
mplayer: this switch is not working, Exist here any alternative to -hr-seek?

**Comment by thebombzen** [comment]
mplayer is not mpv, and it's up to the people who develop mplayer, not us, to fix bugs in mplayer or add features to mplayer. You can find more details about mplayer on [their website](http://mplayerhq.hu/design7/news.html).

**Comment by er512** [comment]
OK, thanks all for info.
