### ISSUE TITLE
Raspberry PI

### ISSUE THREAD

**Issue by wbugar** [mpv-player/mpv.io#68]
Has this been tried on the Pi?

**Comment by lachs0r** [comment]
This is the webpage repository. If this is a question about the mpv software: Yes, it has been tried. Yes, it is sort of supported, but definitely not recommended. The Pi is a waste of time and with absolute certainty won’t perform the way you want it to. If you really hate yourself so much that you want to use one of those terrible ARM platforms, at least get a Tinker Board or something better.
