### ISSUE TITLE
Link to djcj/vapoursynth ppa invalid

### ISSUE THREAD

**Issue by PvB03** [mpv-player/mpv.io#71]
This link listed in the Download section of mpv.io under Ubuntu (with Vapoursynth support) is down: https://launchpad.net/%7Edjcj/+archive/ubuntu/vapoursynth

There is to me currently no way of successfully compiling mpv with Vapoursynth support on 18.04 (I tried for hours). I would really appreciate a ppa with a precompiled mpv + vapoursynth to return.

**Comment by sfan5** [comment]
Link no longer exists.
