### ISSUE TITLE
send command to mpv in powershell

### ISSUE THREAD

**Issue by leichenxu** [mpv-player/mpv.io#72]
hi, i want to ask if is possible to send command to a mpv in cmd or powershell to a video playing in mpv, a video started like this
.\mpv.com --wid=<hwnd> video1.mp4
,and in another powershell or cmd send command to this video playing

**Comment by Akemi** [comment]
this is the issue tracker for the website not the player. you should ask here (https://github.com/mpv-player/mpv) instead.

and yes https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst

**Comment by leichenxu** [comment]
thanks
