### ISSUE TITLE
cannot setup a local development environment

### ISSUE THREAD

**Issue by tasty0tomato** [mpv-player/mpv.io#91]
I want to make a change, and I want to know if I make a right change.
But I cannot setup a local development environment
![cmd_2Ze9ae64fX](https://user-images.githubusercontent.com/48764449/116331177-cb0d1d00-a801-11eb-82cd-873737f4a6c1.png)
Can I just pull the request without a local development.

**Comment by sfan5** [comment]
Should be possible again now, probably.
